# Configurations
title:            Documentación
longtitle:        Documentaciòn del Segundo semestre del segundo modulo
author:           Gastón Genaro Quelali Calcina
email:            gaston.quelali@gmail.com
description: >
  Build Jekyll site with the GitBook style.

version:          1.0
gitbook_version:  3.2.3

url:              'https://gastonquelali.github.io'
baseurl:          '/ucatec'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts
  - _others
  - _posts
  - _sistemas-operativos
  - _redes

collections:
  redes2:
    output: true
    permalink: /redes2/:path/
    label: 'Redes 2'
  administracion-servidores:
    output: true
    permalink: /administracion-servidores/:path/
    label: 'Administración de Servidores' 
  lenguajes-programacion:
    output: true
    permalink: /:collection/:path/
    label: 'Lenguajes de Programación'
  sistemas-operativos:
    output: true
    permalink: /:collection/:path/
    label: 'Sistemas Operativos' 
  pages:
    output: true
    permalink: /:collection/:path/
    label: 'Redes' 
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - redes2
  - administracion-servidores
  - lenguajes-programacion
  - sistemas-operativos
  - posts
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
